### ISSUE TITLE
Cannot read property 'New' of undefined

### ISSUE THREAD

**Issue by reimago** [valor-software/ng2-tree#267]
Hi. Using Angular 6 and building the application for production. When creating the tree it gives this error and the tree is not created. :-(

**Comment by reimago** [comment]
The error seems to occur in:  tree.js.pre-build-optimizer.js: 858.

  function () {
         return this.node._status === tree_types_1.TreeStatus.New;
     };

**Comment by kperdomoc** [comment]
Yes it has to do with angular 6 and it's in production mode only. Was about to deploy an app and this blew everything off. Now, I'm not sure if it's worth waiting a fix or going straight after the new native angular material tree widget.

**Comment by reimago** [comment]
I think it's related to the "buildOptimizer". I turned it off in the file "angular.json" (configurations-> production-> buildOptimizer). I have set it to "false" and now it works for me !! I do not know if it is ng2-tree or buildOptimizer problem. While it is fixed I will leave it deactivated.

**Comment by kperdomoc** [comment]
@reimago thanks I'll give that I try. For now I just downgraded to angular 5 to get things going fast.

**Comment by Misikir** [comment]
The issue is still there. We can't go back to angular 5. Is there any solution for this with Angular 6 AOT @rychkog , @akkumar
